### ISSUE TITLE
Configure DNS record for [www.]repaircafe.nu

### ISSUE THREAD

**Issue by qerub** [repaircafe/malmo.repaircafe.nu#11]
It should redirect to malmo.repaircafe.nu for now.

The redirect can probably be set up in Loopia's administration tool.

Edit: …or using Netlify's _redirect file.

**Comment by monsieurhannes** [comment]
Works

**Comment by qerub** [comment]
@monsieurhannes: Didn't we decide to use malmo.repaircafe.nu? I'd prefer we do it right from the start instead of switching later so that the [URLs won't have to change](https://www.w3.org/Provider/Style/URI).

**Comment by qerub** [comment]
@monsieurhannes: Ping.

**Comment by monsieurhannes** [comment]
Well, if we use `malmö.repaircafe.nu` we still need a `repaircafe.nu`-version. Maybe two repos, one which can be a mirror of the current one (repaircafe.nu) and the other one which we update (malmö.repaircafe.nu). We could already think of `lund.repaircafe.nu` as that's happening very soon.

How could that look like? Each gets its own repo and `repaircafe.nu` has a list of all repair cafes - maybe even a combined calendar and blog with the posts from each RC in the subdomains - that would be amazing!

**Comment by monsieurhannes** [comment]
Or we solve it by having different branches for each subdomain:
https://www.netlify.com/docs/custom-domains/#branch-subdomains

But that sounds quite messy, you can decide.

**Comment by qerub** [comment]
> Well, if we use malmö.repaircafe.nu we still need a repaircafe.nu-version. Maybe two repos, one which can be a mirror of the current one (repaircafe.nu) and the other one which we update (malmö.repaircafe.nu). We could already think of lund.repaircafe.nu as that's happening very soon.
>
> How could that look like? Each gets its own repo and repaircafe.nu has a list of all repair cafes - maybe even a combined calendar and blog with the posts from each RC in the subdomains - that would be amazing!

One repository per website under the common GitHub organization is the way to go. That way we can easily hand over the Lund site to different set of owners. While we're at it and you're messing around with the repositories, I suggest we introduce a (new) name convention. I say we either add the suffix "-website" or use the full domain name ("malmo.repaircafe.nu").

> I added the subdomains to netlify, but I'm not sure if they get connected automatically. Unfortunately loopia doesn't give alot of options.

They got connected. Loopia is only used a domain registrar after you switched to Netlify DNS.

**Comment by monsieurhannes** [comment]
I would say we close the issue as the DNS record is created.
I also renamed the repository. I would say that the other question, how the repos are connected is something for another issue.
