### ISSUE TITLE
Make STPLN link to our web site

### ISSUE THREAD

**Issue by qerub** [repaircafe/malmo.repaircafe.nu#43]
https://stpln.org/repair-cafe-malmo currently only links to our Facebook page.

**Comment by monsieurhannes** [comment]
Just made it worse by changing our handle and therefore the link. But I will inform STPLN about the new link to our homepage.

**Comment by monsieurhannes** [comment]
STPLN is informed, waiting for an answer.

**Comment by qerub** [comment]
@monsieurhannes: They changed the link to http://xn--malm-8qa.repaircafe.nu/ which we haven't set up.

**Comment by monsieurhannes** [comment]
Argh, I wanna die! Previously I sent the wrong link (www.malmo.repaircafe.nu), then, after it was wrong I sent malmö.repaircafe.nu and forgot that it's malmo.repaircafe.nu
I'll write him that I was wrong again -.- superfail!

**Comment by qerub** [comment]
Fixed!
